<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" version="2.0"
  xmlns:fo="http://www.w3.org/1999/XSL/Format"
  >
 <!--  FO output support for the DITA 1.3 Troubleshooting topic type and troubleshooting
       domain.
   -->
   
   <!--  Put required processing here. -->
  

  
<xsl:template match="*[contains(@class, ' troubleshooting/remedy ')]/*[contains(@class, ' task/steps ')]">
    <fo:list-block xsl:use-attribute-sets="steps">
      <xsl:call-template name="commonattributes"/>
      <xsl:apply-templates/>
    </fo:list-block>
  </xsl:template>

  <!-- No autogenerated title for steps-unodered when it's a child of remedy -->
  <xsl:template match="*[contains(@class, ' troubleshooting/remedy ')]/*[contains(@class, ' task/steps-unordered ')]">
    <fo:list-block xsl:use-attribute-sets="steps-unordered">
      <xsl:call-template name="commonattributes"/>
      <xsl:apply-templates/>
    </fo:list-block>
  </xsl:template>

</xsl:stylesheet>
